### ISSUE TITLE
missing name and image/animationUrl properties on latest/newest queries

### ISSUE THREAD

**Issue by preschian** [kodadot/snek#100]
related issues:
- https://github.com/kodadot/nft-gallery/issues/4073
- https://github.com/kodadot/nft-gallery/issues/4102

**Comment by roiLeo** [comment]
could be related with #101, we might need to check null value on `image`

**Comment by roiLeo** [comment]
> missing some name in `collectionEntities`

`meta` field is null we might have some trouble to fetch metadata on some collection. ref:
https://github.com/kodadot/snek/blob/c53c2936ea0dea352fc2b9dfc16d2b77041d1d85/src/mappings/index.ts#L96-L100
&
https://github.com/kodadot/snek/blob/c53c2936ea0dea352fc2b9dfc16d2b77041d1d85/src/mappings/index.ts#L58-L61
