### ISSUE TITLE
Withdraw offer fails when it is called by NFT owner and not by maker

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#127]
```
22/12/2022 11:07:08 PM
Info
}
22/12/2022 11:07:08 PM
Info
  "sn": "2"
22/12/2022 11:07:08 PM
Info
  "collectionId": "331660682",
22/12/2022 11:07:08 PM
Info
  "timestamp": "2022-12-21T14:01:00.180Z",
22/12/2022 11:07:08 PM
Info
  "blockNumber": "1421511",
22/12/2022 11:07:08 PM
Info
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
22/12/2022 11:07:08 PM
Info
⬤  debug     offer no: {
22/12/2022 11:07:08 PM
Critical
sqd:processor ReferenceError: [PROBLEM] Entity  needs to be real
    at needTo (/squid/lib/mappings/utils/consolidator.js:45:15)
    at plsBe (/squid/lib/mappings/utils/consolidator.js:35:12)
    at handleOfferWithdraw (/squid/lib/mappings/index.js:297:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:506:25)
    at async /squid/node_modules/@subsquid/typeorm-store/lib/database.js:157:13
    at async EntityManager.transaction (/squid/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async FullTypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:155:9)
    at async FullTypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
    at async HandlerRunner.processBatch (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:471:13)
22/12/2022 11:12:10 PM
Info
> node lib/processor.js
22/12/2022 11:12:10 PM
Info
> @kodadot1/snek@0.0.4 processor:start
22/12/2022 11:12:11 PM
Warning
sqd:processor .setBatchSize() is deprecated and has no effect
22/12/2022 11:12:11 PM
Info
●  note      Welcome to the Processor! ROCOCO
22/12/2022 11:12:11 PM
Info
sqd:processor last processed block was 1421177
22/12/2022 11:12:11 PM
Info
sqd:processor processing blocks from 1421178
22/12/2022 11:12:12 PM
Info
sqd:processor prometheus metrics are served at port 3000
22/12/2022 11:12:12 PM
Info
☐  pending   [WITHDRAW OFFER]: 1421511
22/12/2022 11:12:12 PM
Info
}
22/12/2022 11:12:12 PM
Info
  "sn": "2"
22/12/2022 11:12:12 PM
Info
  "collectionId": "331660682",
22/12/2022 11:12:12 PM
Info
  "timestamp": "2022-12-21T14:01:00.180Z",
22/12/2022 11:12:12 PM
Info
  "blockNumber": "1421511",
22/12/2022 11:12:12 PM
Info
  "caller": "bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW",
22/12/2022 11:12:12 PM
Info
⬤  debug     offer no: {
22/12/2022 11:12:12 PM
Critical
sqd:processor ReferenceError: [PROBLEM] Entity  needs to be real
    at needTo (/squid/lib/mappings/utils/consolidator.js:45:15)
    at plsBe (/squid/lib/mappings/utils/consolidator.js:35:12)
    at handleOfferWithdraw (/squid/lib/mappings/index.js:297:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HandlerRunner.processBlock (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:506:25)
    at async /squid/node_modules/@subsquid/typeorm-store/lib/database.js:157:13
    at async EntityManager.transaction (/squid/node_modules/typeorm/entity-manager/EntityManager.js:72:28)
    at async FullTypeormDatabase.runTransaction (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:155:9)
    at async FullTypeormDatabase.transact (/squid/node_modules/@subsquid/typeorm-store/lib/database.js:64:24)
    at async HandlerRunner.processBatch (/squid/node_modules/@subsquid/substrate-processor/lib/processor/handlerProcessor.js:471:13)
22/12/2022 11:17:23 PM
Info
```

**Comment by roiLeo** [comment]
Hey! `bXhWeVLtArWauM8UmbaVdDmXmo5uSDk6DAa2YxQ5zbt2sDcbW` that's me.
@kodadot1/snek@0.0.4 so it's happening on Snek more specificaly on `/snek/gallery/331660682-2`
I'll see if I can find a solution but I'll have to reindex everything locally and it will take me some time.

**Comment by vikiival** [comment]
Hey @roiLeo,
thanks for the comment!

> reindex everything locally and it will take me some time. 

It can be done in few min.

According to UI everything should be ok.

**Comment by roiLeo** [comment]
> It can be done in few min.

indeed I just saw that, but still `entity: null`
<img width="746" alt="Capture d’écran 2023-01-02 à 11 15 37 AM" src="https://user-images.githubusercontent.com/9987732/210219019-cf5fcf5e-9879-4621-9565-4d191df94d6b.png">

> According to UI everything should be ok.

withdraw offer looks ok to me on [polkadotjs](https://polkadot.js.org/apps/#/explorer/query/1421511)

is it because it's the first time I've try to `withdraw_offer` as nft currentOwner and not from the caller?

**Comment by vikiival** [comment]
The problem is that somehow token entity is null

**Comment by roiLeo** [comment]
> you're sure it's not because the caller isn't the maker?

Okay, that's where the problem comes from.
It worked for me after hard setting WithDrawOffer Id to `331660682-2-bXmhznuiEieVYtR4RBomyq2zPTQKYBgr4XNCk5i4nid45Y7Xk` 

#### possible solution

- find a way to save offer (`make_offer`) in db without the event caller in ID
- or on withdraw_offer if `currentOwner === caller` find the original `make_offer` event caller

**Comment by vikiival** [comment]
So as I understand the problem:
1. Leo has NFT
2. Viki makes offer
3. Viki buys NFT
4. Viki wants to withdraw offer but it fails?

**Comment by roiLeo** [comment]
> So as I understand the problem:
> 
>     1. Leo has NFT
>     2. Viki makes offer
>     3. Viki buys NFT
>     4. Viki wants to withdraw offer but it fails?

more like:

1. Leo has NFT
2. Viki makes offer
3. Leo Withdraw offer (as nft currentOwner) because it's expired or he doesn't like it
4. subsquid won't save this event while it is well registered on chain

**Comment by vikiival** [comment]
@roiLeo I got it. And you are right.

Only two people have ability to withdraw offer -> `maker` and `currentOwner`


https://github.com/galacticcouncil/Basilisk-node/blob/6b45b2e4a610e5f469fb65b5754b515b7c8a7441/pallets/marketplace/src/lib.rs#L237


as you pointed out correctly SubSquid is looking for Offer with id (`collection-token-caller`) and therefore it is incorrect 

The fix for this:
Get extrinsic of withdraw_offer (We can get that direclty from subsquid) and check (who was the maker)[https://github.com/galacticcouncil/Basilisk-node/blob/6b45b2e4a610e5f469fb65b5754b515b7c8a7441/pallets/marketplace/src/lib.rs#L223]

Steps:
- get `call` as you shown in the snippet above
- from args get `maker`
- extend our event with `maker` field or replace the caller with the value you got from `maker`
- everything else should work smoothly.

Thanks for the research! Outstanding job ^-^ ❤️

**Comment by roiLeo** [comment]
### Steps:

> * get `call` as you shown in the snippet above

How? And Where? from `getWithdrawOfferEvent`? or in `MarketplaceOfferWithdrawnEvent`?
 I am lost with these isV55, isV75 idk what that means
 
> * from args get `maker`

`event.call.args`? How can I read this data?

> * extend our event with `maker` field or replace the caller with the value you got from `maker`

I think I understand this part

**Comment by vikiival** [comment]
> get call as you shown in the snippet above

Yes from `MarketplaceOfferWithdrawnEvent` and implement in `getWithdrawOfferEvent`

> I am lost with these isV55, isV75 idk what that means

It means that the event has different version. (due to forkless upgrades of substrate)

> event.call.args? How can I read this data? 

Should be object that will contain field `maker`

**Comment by roiLeo** [comment]
Now I have another issue on block [1434377](https://polkadot.js.org/apps/#/explorer/query/1434377)

token `331660682-331660682` doesn't exist idk why it's sending this

```bash
☐  pending   [PLACE OFFER]: 1434377
⬤  debug     offer:  {
  caller: 'bXhZ9xjHQm7QqZvByGVWaA1ExYCNKeeAHmZJL1ZSSvMqSo3Xu',
  blockNumber: '1434377',
  timestamp: 2022-12-23T09:03:18.159Z,
  collectionId: '331660682',
  sn: '331660682',
  amount: 30000000000n,
  expiresAt: 1441577n
}
⬤  debug     tokenId: 331660682-331660682
14:56:02 FATAL sqd:processor ReferenceError: [PROBLEM] Entity  needs to be real
```

`sn` value is wrong, it should be itemId
Does it have something to do with "different version"?
