### ISSUE TITLE
Bug report: Create on chain identity fails and shows weird popup

### ISSUE THREAD

**Issue by cryptodamsky** [kodadot/snek#139]
Reproducing in steps:

- Went to beta.kodadot.xyz / Basilisk chain
- Clicked on Profile, create on chain identity
- This pops up

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/92786519/214809960-eff1f444-b58c-4488-bb82-9931e8384dc5.png">

Browser: Chrome
Wallet: PolkadotJS

**Comment by roiLeo** [comment]
maybe `kodadot.merchandise@protonmail.com` address is too long (max 32chars)

**Comment by cryptodamsky** [comment]
This address is used on other identities without problem

**Comment by roiLeo** [comment]
> This address is used on other identities without problem, but on Kusama

I made a couple test with long address (more thant 32chars) and it didn't worked, small address worked
Did you try to set it through [Polkadot js](https://polkadot.js.org/) app?

IMO this issue is not related with Kodadot but rather with bsx or subtrate team

**Comment by cryptodamsky** [comment]
> > This address is used on other identities without problem, but on Kusama
> 
> I made a couple test with long address (more thant 32chars) and it didn't worked, small address worked Did you try to set it through [Polkadot js](https://polkadot.js.org/) app?
> 
> IMO this issue is not related with Kodadot but rather with bsx or subtrate team

Yes, but we allow to input longer email address in the filed and therefore it’s showing bug on our site. We should at least specify this to avoid confusion or limit the number of characters
