### ISSUE TITLE
Resolver for stats of collection

### ISSUE THREAD

**Issue by Jarsen136** [kodadot/snek#142]
Requirement
- extends `collectionEntitiesConnection` resolver or provide a new resolver
- input:
```javascript
{
    offset
    limit
    where
    orderBy
}
```

- output:
```javascript
{
   volume:  xxx, // Total trading turnover
   highestSale: xxx, // Maximum selling price
   totalCount: xxx     // count of nfts in this colleciton
}
```

<img width="300" alt="image" src="https://user-images.githubusercontent.com/31397967/219848642-6a5394fc-a493-42dc-a47e-e543d061f266.png">

**Comment by roiLeo** [comment]
related with #33?

**Comment by Jarsen136** [comment]
> related with #33?

They are a little bit related, though, in this issue, we focus on every single one collection stats in the list.

**Comment by alko89** [comment]
Think `totalCount` is already there -> `nftCount`
