### ISSUE TITLE
Metada fail for snek

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#164]
```graphql
query x {
  collectionEntitiesConnection(orderBy: name_ASC, where: { name_containsInsensitive: "Rare"}) {
    totalCount
  }
  collectionEntities(orderBy: name_ASC, where: { issuer_eq: "bXm3fZoQkHNgt74RQfL9o4rbtbH7tSaHZnJAYtipTxR9qNFo4" }) {
    name
  }
}
```

```json
{
  "data": {
    "collectionEntitiesConnection": {
      "totalCount": 10
    },
    "collectionEntities": [
      {
        "name": "Basilisk Sama"
      },
      {
        "name": "Basilisk Sama"
      },
      {
        "name": "[[ Rare Waifu ]]"
      },
      {
        "name": "[[ Rare Waifu ]]"
      },
      {
        "name": "[[ Rare Waifu ]]"
      },
      {
        "name": "[[ Rare Waifu ]]"
      },
      {
        "name": "[[ Rare Waifu ]]"
      },
      {
        "name": "[[ Rare Waifu ]]"
      }
    ]
  }
}
```

ref:

- https://github.com/kodadot/nft-gallery/issues/5266

**Comment by roiLeo** [comment]
ain't something related with https://github.com/kodadot/snek/blob/f38aba12187b62b0653923946cd4326cc95120fa/src/mappings/utils/metadata.ts#L14

you told me somewhere that it won't work on snek

**Comment by roiLeo** [comment]
> It should work on snek I do not see any magic with that.
> 
> Anyway I made a hard reset so we will see.

Already tryed to reindex on local and I still have same result maybe revert this one #161

**Comment by vikiival** [comment]
most probably what is going on is that I forgot to return metadata from `getters.ts` if you can please check it would be nice

**Comment by roiLeo** [comment]
> most probably what is going on is that I forgot to return metadata from `getters.ts` if you can please check it would be nic

How do you work with this event type? And how do you know when BSX team add new event version?
this part is still unclear to me

**Comment by vikiival** [comment]
> And how do you know when BSX team add new event version?

Usually the indexer fails 😅 

> How do you work with this event type?

I need to do 

```
just typegen
just build
```

and then integrate rest
