### ISSUE TITLE
I'm getting this error since yesterday

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#180]
I'm getting this error since yesterday

![image](https://github.com/kodadot/nft-gallery/assets/734428/60247eda-92b6-43b7-94c8-7ca983c13428)

_Originally posted by @preschian in https://github.com/kodadot/nft-gallery/issues/6125#issuecomment-1569584595_

**Comment by vikiival** [comment]
<img width="896" alt="Screenshot 2023-06-01 at 20 57 05" src="https://github.com/kodadot/snek/assets/22471030/6332b60c-c290-4885-b7ef-74dd0cb71425">

![Screenshot 2023-06-01 at 20 55 22](https://github.com/kodadot/snek/assets/22471030/a77c9e48-3d38-4eef-bb37-4b2808dcb397)

**Comment by Matehoo** [comment]
None of the above issues appear upon testing.
