### ISSUE TITLE
Snek stuck once again (/snek)

### ISSUE THREAD

**Issue by roiLeo** [kodadot/snek#182]
https://squiki.kodadot.workers.dev/status/snekk

current block atm [2,246,977](https://polkadot.js.org/apps/#/explorer/query/0xcf63b4026e802585318bcf310e4526aca8dbf296c3088a56a693120f573515f6)

```log
INFO  sqd:processor last processed block was 2238879
INFO  sqd:processor processing blocks from 2238880
```

maybe something wrong with bsx testnet

**Comment by vikiival** [comment]
can we close?
Since we use sneck

**Comment by roiLeo** [comment]
> can we close? Since we use sneck

Sure 🚀

**Comment by roiLeo** [comment]
Btw how do you manage release now?

**Comment by vikiival** [comment]
Same as before

release-*

Wheere squid is basilisk
Ans snek is rococo
