### ISSUE TITLE
[Loligo#47] Add indexes to sort fields

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#190]
<img width="696" alt="Screenshot 2023-09-05 at 13 10 14" src="https://github.com/kodadot/loligo/assets/22471030/4e0093ba-1bb1-47f2-942b-59f1245621c7">

What to do? 

for collection fields add index to:

<img width="266" alt="Screenshot 2023-09-05 at 13 12 24" src="https://github.com/kodadot/loligo/assets/22471030/ff123e39-7d83-48ad-9bc9-65467ca09f45">

```graphql
type CollectionEntity @entity {
  createdAt: DateTime!
  distribution: Int!
  floor: BigInt!
  updatedAt: DateTime!
  nftCount: Int!
  supply: Int!
  volume: BigInt!
}

````

On NFT Entity

```graphql
type NFTEntity @entity {
  burned: Boolean!
  createdAt: DateTime!
  name: String @index
  price: BigInt
  updatedAt: DateTime!
}
```

Tasks:
- [ ] [update selected fields with index](https://docs.subsquid.io/firesquid/basics/schema-file/indexes-and-constraints/)
- [ ] perform a migration
- [ ] do PR for (stick/rubick/snek)

Parent:
- kodadot/loligo#47

**Comment by vikiival** [comment]
cannot assign @roiLeo

**Comment by roiLeo** [comment]
👋 👁️ 👄 👁️

**Comment by roiLeo** [comment]
From what I know, SQL doesn't need index for order_by since it already run the query before sorting/grouping but I'm still going to try.
