### ISSUE TITLE
Cannot create unique index on the blocknumber

### ISSUE THREAD

**Issue by vikiival** [kodadot/snek#195]
```
query: 'CREATE UNIQUE INDEX "IDX_8fed68c917920ff529994c2c65" ON "nft_entity" ("block_number") ',
```

https://github.com/kodadot/snek/blame/62b798997e3de0222845ff16cbcddff4e9cfa2b6/schema.graphql#L29

cc @roiLeo

**Comment by roiLeo** [comment]
Blocknumber not unique? multiple tx in one block? same as AssetHub?

**Comment by vikiival** [comment]
For all chains
