### ISSUE TITLE
Destroy a class ( collection ) 

### ISSUE THREAD

**Issue by petersopko** [kodadot/snek#35]
Destroys a previously created class. In our implementation, such a class cannot contain any minted tokens inside. 
linking from https://github.com/kodadot/nft-gallery/issues/660

**Comment by vikiival** [comment]
This is already implemented dbe2b3b38b33bdfa2b16d167e0e391940f560acb

**Comment by vikiival** [comment]
dbe2b3b38b33bdfa2b16d167e0e391940f560acb

**Comment by petersopko** [comment]
oh, mb
