### ISSUE TITLE
Gift event should cancel Listing?

### ISSUE THREAD

**Issue by petersopko** [kodadot/snek#56]
follow up from here:
https://github.com/kodadot/nft-gallery/issues/3687

I've tested this myself, here's a link to the NFT https://beta.kodadot.xyz/bsx/gallery/1703103244-3

**Comment by vikiival** [comment]
This should be implemeted by either:
- [ ] in Basilisk Node as extension of the runtime pallet
- [ ] in KodaDot NFT gallery that should perform `batchAll[unlist, transfer]`
