### ISSUE TITLE
Mass burn on handleCollectionDestroy

### ISSUE THREAD

**Issue by roiLeo** [kodadot/snek#90]
I would like to be able on `handleCollectionDestroy` to check if the tokens are Burned and if not then Burn them 🔥

**Comment by vikiival** [comment]
This should not happen tbh

**Comment by vikiival** [comment]
Also on collection destroy I would literally remove the whole collection

**Comment by roiLeo** [comment]
> This should not happen tbh

Should be done on the frontend?
I've been wondering for a while if it was possible to do several actions with a single wallet signature

> Also on collection destroy I would literally remove the whole collection

on `NFT.ClassDestroyed` (destroy_collection) there is no side effect regarding the tokens inside?

**Comment by vikiival** [comment]
> This should not happen tbh

@roiLeo I meant that Collection can be destroyed only when all NFTs are burned

> on NFT.ClassDestroyed (destroy_collection) there is no side effect regarding the tokens inside?

Currently no

**Comment by roiLeo** [comment]
closing this one for kodadot/nft-gallery#938
